# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/julio/Desktop/SIMNAV/simnav/gui/base/ui/configuracion.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Configuracion(object):
    def setupUi(self, Configuracion):
        Configuracion.setObjectName("Configuracion")
        Configuracion.resize(873, 413)
        Configuracion.setMinimumSize(QtCore.QSize(873, 413))
        Configuracion.setMaximumSize(QtCore.QSize(873, 413))
        Configuracion.setBaseSize(QtCore.QSize(932, 570))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        Configuracion.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(Configuracion)
        self.gridLayout_2.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Configuracion)
        self.tabWidget.setMaximumSize(QtCore.QSize(912, 516))
        self.tabWidget.setObjectName("tabWidget")
        self.tabCompuestos = QtWidgets.QWidget()
        self.tabCompuestos.setObjectName("tabCompuestos")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabCompuestos)
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.tabCompuestos)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.buscarEdit = QtWidgets.QLineEdit(self.tabCompuestos)
        self.buscarEdit.setObjectName("buscarEdit")
        self.horizontalLayout_3.addWidget(self.buscarEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.compuestosTabla = QtWidgets.QTableWidget(self.tabCompuestos)
        self.compuestosTabla.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.compuestosTabla.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.compuestosTabla.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.compuestosTabla.setDragEnabled(True)
        self.compuestosTabla.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.compuestosTabla.setTextElideMode(QtCore.Qt.ElideLeft)
        self.compuestosTabla.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.compuestosTabla.setRowCount(1)
        self.compuestosTabla.setColumnCount(3)
        self.compuestosTabla.setObjectName("compuestosTabla")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.compuestosTabla.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.compuestosTabla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.compuestosTabla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.compuestosTabla.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.compuestosTabla.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.compuestosTabla.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.compuestosTabla.setItem(0, 2, item)
        self.compuestosTabla.horizontalHeader().setVisible(False)
        self.compuestosTabla.horizontalHeader().setCascadingSectionResizes(False)
        self.compuestosTabla.horizontalHeader().setDefaultSectionSize(130)
        self.compuestosTabla.horizontalHeader().setMinimumSectionSize(70)
        self.compuestosTabla.horizontalHeader().setStretchLastSection(True)
        self.compuestosTabla.verticalHeader().setVisible(False)
        self.compuestosTabla.verticalHeader().setCascadingSectionResizes(False)
        self.compuestosTabla.verticalHeader().setDefaultSectionSize(45)
        self.compuestosTabla.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.compuestosTabla)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.tabCompuestos)
        self.widget.setMinimumSize(QtCore.QSize(100, 0))
        self.widget.setObjectName("widget")
        self.agregarCompuesto = QtWidgets.QPushButton(self.widget)
        self.agregarCompuesto.setGeometry(QtCore.QRect(0, 0, 99, 27))
        self.agregarCompuesto.setObjectName("agregarCompuesto")
        self.eliminarCompuesto = QtWidgets.QPushButton(self.widget)
        self.eliminarCompuesto.setGeometry(QtCore.QRect(0, 30, 99, 27))
        self.eliminarCompuesto.setObjectName("eliminarCompuesto")
        self.borrarLista = QtWidgets.QPushButton(self.widget)
        self.borrarLista.setGeometry(QtCore.QRect(0, 60, 99, 27))
        self.borrarLista.setObjectName("borrarLista")
        self.gridLayout_4.addWidget(self.widget, 1, 1, 1, 1)
        self.compuestosSeleccionadosList = QtWidgets.QListWidget(self.tabCompuestos)
        self.compuestosSeleccionadosList.setMaximumSize(QtCore.QSize(200, 16777215))
        self.compuestosSeleccionadosList.setDragDropOverwriteMode(True)
        self.compuestosSeleccionadosList.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.compuestosSeleccionadosList.setObjectName("compuestosSeleccionadosList")
        self.gridLayout_4.addWidget(self.compuestosSeleccionadosList, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tabCompuestos)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_4)
        self.tabWidget.addTab(self.tabCompuestos, "")
        self.propiedades = QtWidgets.QWidget()
        self.propiedades.setObjectName("propiedades")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.propiedades)
        self.horizontalLayout_5.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.propiedades)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.paquetesDisponibles = QtWidgets.QListWidget(self.propiedades)
        self.paquetesDisponibles.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.paquetesDisponibles.setObjectName("paquetesDisponibles")
        item = QtWidgets.QListWidgetItem()
        self.paquetesDisponibles.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.paquetesDisponibles.addItem(item)
        self.verticalLayout_3.addWidget(self.paquetesDisponibles)
        self.label_5 = QtWidgets.QLabel(self.propiedades)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.paqueteSeleccionado = QtWidgets.QListWidget(self.propiedades)
        self.paqueteSeleccionado.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.paqueteSeleccionado.setObjectName("paqueteSeleccionado")
        self.verticalLayout_3.addWidget(self.paqueteSeleccionado)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.descripcionPaquete = QtWidgets.QLabel(self.propiedades)
        self.descripcionPaquete.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.descripcionPaquete.setObjectName("descripcionPaquete")
        self.horizontalLayout.addWidget(self.descripcionPaquete)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.propiedades, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Configuracion)
        QtCore.QMetaObject.connectSlotsByName(Configuracion)

    def retranslateUi(self, Configuracion):
        _translate = QtCore.QCoreApplication.translate
        Configuracion.setWindowTitle(_translate("Configuracion", "Form"))
        self.label.setText(_translate("Configuracion", "Buscar"))
        self.compuestosTabla.setSortingEnabled(True)
        item = self.compuestosTabla.verticalHeaderItem(0)
        item.setText(_translate("Configuracion", "1"))
        item = self.compuestosTabla.horizontalHeaderItem(0)
        item.setText(_translate("Configuracion", "Nombre"))
        item = self.compuestosTabla.horizontalHeaderItem(1)
        item.setText(_translate("Configuracion", "Nombre (Inglés)"))
        item = self.compuestosTabla.horizontalHeaderItem(2)
        item.setText(_translate("Configuracion", "Formula Molecular"))
        __sortingEnabled = self.compuestosTabla.isSortingEnabled()
        self.compuestosTabla.setSortingEnabled(False)
        item = self.compuestosTabla.item(0, 0)
        item.setText(_translate("Configuracion", "asd"))
        item = self.compuestosTabla.item(0, 1)
        item.setText(_translate("Configuracion", "asd"))
        item = self.compuestosTabla.item(0, 2)
        item.setText(_translate("Configuracion", "asd"))
        self.compuestosTabla.setSortingEnabled(__sortingEnabled)
        self.agregarCompuesto.setText(_translate("Configuracion", "Agregar >>"))
        self.eliminarCompuesto.setText(_translate("Configuracion", "<< Eliminar"))
        self.borrarLista.setText(_translate("Configuracion", "Borrar Lista"))
        self.label_2.setText(_translate("Configuracion", "Seleccione los componentes a utilizar en la simulación"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCompuestos), _translate("Configuracion", "Compuestos"))
        self.label_3.setText(_translate("Configuracion", "Seleccione el paquete de propiedades a utilizar en la simulación"))
        __sortingEnabled = self.paquetesDisponibles.isSortingEnabled()
        self.paquetesDisponibles.setSortingEnabled(False)
        item = self.paquetesDisponibles.item(0)
        item.setText(_translate("Configuracion", "Ideal"))
        item = self.paquetesDisponibles.item(1)
        item.setText(_translate("Configuracion", "Peng-Robison"))
        self.paquetesDisponibles.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("Configuracion", "Seleccionado"))
        self.descripcionPaquete.setText(_translate("Configuracion", "Descripcion extensiva de lo que contiene el paquete de propiedades\n"
"Al clickearlo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.propiedades), _translate("Configuracion", "Propiedades"))


